# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: cirrusci/flutter

pipelines:
  default:
    - step:
        name: 'Install packages and run lints & tests'
        script:
          - flutter pub get
          - flutter test