name: flutter_uv_blind_refactor
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.2+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # local_hero: ^0.2.0
  amazon_cognito_identity_dart_2: ^1.0.3
  app_group_directory: ^2.0.0
  app_settings: 4.1.1
  audio_session: ^0.1.6+1
  auto_size_text: ^3.0.0
  background_location: ^0.8.1
  cached_network_image: ^3.1.0
  collection: ^1.15.0
  community_material_icon: ^5.9.55
  copy_with_extension: ^2.0.2
  crypto: ^3.0.1
  device_preview: ^1.0.0
  dio: ^4.0.0
  drift: ^1.1.0
  dropdown_button2: ^1.0.7
  easy_localization: ^3.0.0
  encrypt: ^5.0.1
  firebase_analytics: ^8.3.2
  firebase_core: ^1.6.0
  firebase_remote_config: ^0.11.0+1
  flutter_compass: ^0.6.1
  flutter_easyloading: ^3.0.0
  flutter_html: ^2.2.1
  flutter_mailer: ^2.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  flutter_tts: ^3.2.2
  geolocator: ^7.7.1
  get: ^4.5.1
  hive: ^2.0.4
  html: ^0.15.0
  http: ^0.13.3
  invert_colors: ^0.0.3-null-safety.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  just_audio: ^0.9.5
  lazy_load_scrollview: ^1.3.0
  logger: ^1.0.0
  maps_launcher: ^2.0.0
  moor_db_viewer: ^5.0.0
  onesignal_flutter: 3.2.0
  package_info_plus: ^1.0.6
  path_provider: ^2.0.2
  path: ^1.8.0
  permission_handler: ^8.3.0
  retrofit: ^2.0.0
  shake: ^1.0.1
  share: ^2.0.4
  shimmer: ^2.0.0
  sigv4: ^5.0.0
  speech_to_text: ^5.1.1
  sqlite3_flutter_libs: ^0.5.1
  string_splitter: ^1.0.0+1
  uni_links: ^0.5.1
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  vibration: ^1.7.4-nullsafety.0
  wakelock: ^0.5.6
  webview_flutter: ^2.0.10
  flutter_camera_uv_decoder:
    git:
      url: https://nhthang-skglobal:3CbvcHmxejmNfz2wamqG@bitbucket.org/skglobal/flutter_camera_uv_decoder.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  copy_with_extension_gen: ^2.0.3
  drift_dev: ^1.1.0
  image_res: ^0.3.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.1.8+4
  lint: ^1.5.3
  build_runner: ^2.0.6
  retrofit_generator: ^2.0.0+3
  hive_generator: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/launcher_icons/
    - assets/images/icons/
    - assets/images/screenshots/
    - assets/images/icons/brightness/
    - assets/images/miscs/
    - assets/svgs/icons/
    - assets/svgs/icons/menu_icons/
    - assets/svgs/icons/category_icons/
    - assets/sounds/
    - assets/translations/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.otf
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Light.otf
        - asset: assets/fonts/NotoSansJP-Medium.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Thin.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
